name: Generate templates

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  run:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set git config
        run: |
          git config user.name RedCraft.org
          git config user.email contact@redcraft.org

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Settings
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMON_MYSQL_PASSWORD: ${{ secrets.COMMON_MYSQL_PASSWORD }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DEEPL_TOKEN: ${{ secrets.DEEPL_TOKEN }}
          SENTRY_DSN_HUB: ${{ secrets.SENTRY_DSN_HUB }}
          SENTRY_DSN_CREA_REDSTONE_PLOT: ${{ secrets.SENTRY_DSN_CREA_REDSTONE_PLOT }}
          SENTRY_DSN_CREA_BUILD_PLOT: ${{ secrets.SENTRY_DSN_CREA_BUILD_PLOT }}
          SENTRY_DSN_MUSEUM: ${{ secrets.SENTRY_DSN_MUSEUM }}
          MCSYNC_KABAME_KEY: ${{ secrets.MCSYNC_KABAME_KEY }}
        run: |
          ./setup.sh
          source env/bin/activate
          python generate_templates.py
          python check_updates.py
